// Package powerusyservice GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package powerusyservice

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Alao Ramon, Nabil Abubakar",
            "url": "http://www.swagger.io/support",
            "email": "alao.adebusy@gmail.com, nabbo247@yahoo.com"
        },
        "license": {
            "name": "AddyTech Solution Ltd",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Gets the status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Shows the new status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/company/CompanyRegistration": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "Register new company",
                "parameters": [
                    {
                        "description": "Company details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CompanyDetailsIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/api/company/GetComplaintByRefID/{Email}/{CompanyName}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "Gets company details bycompany name.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CompanyDetailsOut"
                        }
                    }
                }
            }
        },
        "/api/company/GetComplaintByRefID/{email}/{companyname}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "Gets company details by email address and company name.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CompanyDetailsOut"
                        }
                    }
                }
            }
        },
        "/api/company/UploadCompanyDocuments": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "Upload company document",
                "parameters": [
                    {
                        "description": "Upload company document",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ImportationDocumentIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/api/users/CheckEmailWithAuthCode/{email}/{authcode}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "validates email with authentication code",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/api/users/CreateNewUser": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Creates new user",
                "parameters": [
                    {
                        "description": "User Details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserOut"
                        }
                    }
                }
            }
        },
        "/api/users/GetAllUsers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "gets list of all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.UserOut"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/GetUserDetailsByEmail/{email}": {
            "get": {
                "description": "gets user details by email address.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "gets user details by email address.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Tbl_users"
                        }
                    }
                }
            }
        },
        "/api/users/GetUserDetailsByUsername/{username}": {
            "get": {
                "description": "Gets user details by username.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Gets user details by username.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Tbl_users"
                        }
                    }
                }
            }
        },
        "/api/users/Login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "log user into the syste",
                "parameters": [
                    {
                        "description": "Login user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserOut"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CompanyDetailsIn": {
            "type": "object",
            "properties": {
                "AccountNumber": {
                    "type": "string"
                },
                "Approvalcomment": {
                    "type": "string"
                },
                "BankName": {
                    "type": "string"
                },
                "CompanyAddress": {
                    "type": "string"
                },
                "CompanyLocation": {
                    "type": "string"
                },
                "CompanyLogo": {
                    "type": "string"
                },
                "CompanyName": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "PostAddress": {
                    "type": "string"
                },
                "ServiceId": {
                    "type": "integer"
                },
                "StatusId": {
                    "type": "integer"
                },
                "UserId": {
                    "type": "integer"
                },
                "WorkingDays": {
                    "type": "string"
                },
                "WorkingHours": {
                    "type": "string"
                }
            }
        },
        "models.CompanyDetailsOut": {
            "type": "object",
            "properties": {
                "AccountNumber": {
                    "type": "string"
                },
                "Approvalcomment": {
                    "type": "string"
                },
                "ApprovedBy": {
                    "type": "integer"
                },
                "BankName": {
                    "type": "string"
                },
                "CompanyAddress": {
                    "type": "string"
                },
                "CompanyLocation": {
                    "type": "string"
                },
                "CompanyLogo": {
                    "type": "string"
                },
                "CompanyName": {
                    "type": "string"
                },
                "Dateadded": {
                    "type": "string"
                },
                "Dateapproved": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "PostAddress": {
                    "type": "string"
                },
                "ServiceId": {
                    "type": "integer"
                },
                "StatusId": {
                    "type": "integer"
                },
                "UserId": {
                    "type": "integer"
                },
                "WorkingDays": {
                    "type": "string"
                },
                "WorkingHours": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.ImportationDocumentIn": {
            "type": "object",
            "properties": {
                "DocumentName": {
                    "type": "string"
                },
                "DocumentPath": {
                    "type": "string"
                },
                "ImportationId": {
                    "type": "string"
                }
            }
        },
        "models.LoginIn": {
            "type": "object",
            "properties": {
                "Password": {
                    "type": "string"
                },
                "Username": {
                    "type": "string"
                }
            }
        },
        "models.ResponseMessage": {
            "type": "object",
            "properties": {
                "responseCode": {
                    "type": "string"
                },
                "responseMessage": {
                    "type": "string"
                }
            }
        },
        "models.Tbl_users": {
            "type": "object",
            "properties": {
                "authcode": {
                    "type": "string"
                },
                "dateAdded": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastname": {
                    "type": "string"
                },
                "middlename": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phonenumber": {
                    "type": "string"
                },
                "roleid": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserIn": {
            "type": "object",
            "properties": {
                "Email": {
                    "type": "string"
                },
                "Firstname": {
                    "type": "string"
                },
                "Lastname": {
                    "type": "string"
                },
                "Middlename": {
                    "type": "string"
                },
                "Password": {
                    "type": "string"
                },
                "Phonenumber": {
                    "type": "string"
                },
                "Username": {
                    "type": "string"
                }
            }
        },
        "models.UserOut": {
            "type": "object",
            "properties": {
                "Accountnumber": {
                    "type": "string"
                },
                "Approvedby": {
                    "type": "string"
                },
                "Dateapproved": {
                    "type": "string"
                },
                "Statusid": {
                    "type": "string"
                },
                "authcode": {
                    "type": "string"
                },
                "dateadded": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastname": {
                    "type": "string"
                },
                "middlename": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phonenumber": {
                    "type": "string"
                },
                "roleid": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8060",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Powerusy backend service",
	Description:      "This is a backend web service created for Powerusy operations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
